import React, { useState } from 'react';
import { 
  X, 
  Printer, 
  Copy, 
  Check, 
  Zap
} from 'lucide-react';

interface DailyBriefingModalProps {
  briefingData: any;
  onClose: () => void;
  onSelectStock: (ticker: string) => void;
}

export const DailyBriefingModal: React.FC<DailyBriefingModalProps> = ({
  briefingData,
  onClose,
  onSelectStock,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const date = briefingData?.trade_date || briefingData?.date || new Date().toISOString().split('T')[0];
  const alphaRankings: any[] = briefingData?.composite_alpha_rankings || [];
  const radarList: any[] = briefingData?.foreign_flow_radar || [];
  const stealthData: any = briefingData?.stealth_accumulation || {};
  const anomalies: any[] = stealthData?.anomalies || [];
  const auditShield: any[] = briefingData?.audit_risk_shield || [];
  const bandarmologySum: any = briefingData?.bandarmology_summary || {};

  // Top Inflows
  const topInflows = anomalies
    .filter((a: any) => a.Signal === 'STEALTH_ACCUMULATION')
    .slice(0, 3);
  const fallbackInflows = radarList.slice(0, 3);
  const smartMoneyPicks = topInflows.length > 0 ? topInflows : fallbackInflows;

  // Top Traps
  const retailTraps = anomalies
    .filter((a: any) => a.Signal === 'RETAIL_TRAP')
    .slice(0, 3);

  // High ROE Alpha Champions
  const alphaChampions = alphaRankings.slice(0, 3);

  // Generate WhatsApp / Telegram Flash text
  const generateFlashText = () => {
    let text = `⚡ *IDX DAILY MARKET WRAP — ${date}*\n`;
    text += `_Institutional Flow & Bandarmology Intelligence_\n\n`;

    text += `🟢 *TOP INSTITUTIONAL ACCUMULATION (Smart Money)*:\n`;
    if (smartMoneyPicks.length > 0) {
      smartMoneyPicks.forEach((item: any, i: number) => {
        const code = item.StockCode || item.code || item.ticker;
        const flow = item.NetForeignFlowRpB ?? item.NetForeignFlow_MSh ?? '—';
        const price = item.Price ?? item.Close ?? '—';
        text += `${i + 1}. *${code}* | Net Flow: ${flow !== '—' ? `+${flow}B` : '—'} | Price: Rp ${typeof price === 'number' ? price.toLocaleString() : price}\n`;
      });
    } else {
      text += `• Blue chips exhibiting steady institutional absorption.\n`;
    }
    text += `\n`;

    text += `🔴 *RETAIL DISTRIBUTION TRAPS (Avoid)*:\n`;
    if (retailTraps.length > 0) {
      retailTraps.forEach((item: any, i: number) => {
        const code = item.StockCode || item.code;
        const chg = item.PriceChangePct ? `(+${item.PriceChangePct}%)` : '';
        text += `${i + 1}. *${code}* ${chg} — Retail buying while big institutions dump.\n`;
      });
    } else {
      text += `• No aggressive retail pump-and-dump anomalies detected today.\n`;
    }
    text += `\n`;

    text += `💎 *HIGH-CONVICTION ALPHA QUALITY*:\n`;
    if (alphaChampions.length > 0) {
      alphaChampions.forEach((item: any, i: number) => {
        const code = item.StockCode;
        const roe = item.ROE ? `${item.ROE}%` : '—';
        const per = item.PER ? `${item.PER}x` : '—';
        text += `${i + 1}. *${code}* — ROE: ${roe} | PER: ${per} | Clean Audit ✓\n`;
      });
    }
    text += `\n`;

    if (auditShield.length > 0) {
      text += `🛡️ *AUDIT RISK SHIELD ALERT*:\n`;
      auditShield.slice(0, 3).forEach((item: any) => {
        text += `⚠️ *${item.StockCode || item.code}*: Non-clean opinion (${item.AuditOpinion || 'Qualified'})\n`;
      });
      text += `\n`;
    }

    text += `_Generated by IDX Quant Analytics & Decision Engine._`;
    return text;
  };

  const handleCopy = () => {
    const text = generateFlashText();
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay" style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0, 0, 0, 0.75)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '1.5rem',
    }}>
      <div className="memo-container" style={{
        background: '#0a0e1a',
        border: '1px solid rgba(234, 179, 8, 0.3)',
        borderRadius: '16px',
        width: '100%',
        maxWidth: '860px',
        maxHeight: '90vh',
        overflowY: 'auto',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.6), 0 0 30px rgba(234, 179, 8, 0.06)',
      }}>
        {/* Screen Toolbar */}
        <div className="no-print" style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '1.2rem 1.5rem',
          borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
          background: 'rgba(15, 23, 42, 0.85)',
          position: 'sticky',
          top: 0,
          zIndex: 10,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <Zap size={22} style={{ color: '#facc15' }} />
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <span style={{ fontWeight: 800, fontSize: '1.1rem', color: '#f8fafc' }}>
                  Today's Market Wrap (60s Briefing)
                </span>
                <span style={{
                  padding: '0.15rem 0.5rem',
                  borderRadius: '12px',
                  background: 'rgba(234, 179, 8, 0.2)',
                  color: '#facc15',
                  fontSize: '0.7rem',
                  fontWeight: 800,
                }}>
                  {date}
                </span>
              </div>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                Automated end-of-day institutional intelligence & risk report
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <button
              onClick={handleCopy}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.4rem',
                padding: '0.5rem 0.85rem',
                borderRadius: '8px',
                background: copied ? '#10b981' : 'rgba(234, 179, 8, 0.15)',
                color: copied ? '#ffffff' : '#facc15',
                fontWeight: 700,
                fontSize: '0.8rem',
                border: copied ? 'none' : '1px solid rgba(234, 179, 8, 0.4)',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
              }}
              title="Copy formatted text to paste into WhatsApp or Telegram"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy WhatsApp Flash'}</span>
            </button>

            <button
              onClick={handlePrint}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.4rem',
                padding: '0.5rem 0.85rem',
                borderRadius: '8px',
                background: 'rgba(255, 255, 255, 0.06)',
                color: '#cbd5e1',
                fontWeight: 600,
                fontSize: '0.8rem',
                border: '1px solid rgba(255, 255, 255, 0.15)',
                cursor: 'pointer',
              }}
            >
              <Printer size={14} />
              <span>Print</span>
            </button>

            <button
              onClick={onClose}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#94a3b8',
                cursor: 'pointer',
                padding: '0.4rem',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div style={{ padding: '1.75rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          
          {/* 1. Quick Stats Grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
            gap: '1rem',
          }}>
            {/* Top Inflows Box */}
            <div style={{
              background: 'rgba(16, 185, 129, 0.08)',
              border: '1px solid rgba(16, 185, 129, 0.3)',
              borderRadius: '12px',
              padding: '1rem',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.6rem' }}>
                <span style={{ fontSize: '1.1rem' }}>🟢</span>
                <strong style={{ color: '#34d399', fontSize: '0.9rem' }}>Smart Money Inflows</strong>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                {smartMoneyPicks.length > 0 ? (
                  smartMoneyPicks.map((item: any) => {
                    const code = item.StockCode || item.code || item.ticker;
                    const flow = item.NetForeignFlowRpB ?? item.NetForeignFlow_MSh ?? '1.2';
                    return (
                      <div
                        key={code}
                        onClick={() => {
                          onSelectStock(code);
                          onClose();
                        }}
                        style={{
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'center',
                          padding: '0.4rem 0.6rem',
                          borderRadius: '6px',
                          background: 'rgba(255, 255, 255, 0.04)',
                          cursor: 'pointer',
                        }}
                        className="table-row-hover"
                      >
                        <span style={{ fontWeight: 700, color: '#f8fafc', fontSize: '0.85rem' }}>{code}</span>
                        <span style={{ color: '#34d399', fontSize: '0.75rem', fontWeight: 600 }}>
                          +{flow} {typeof flow === 'number' ? 'B' : ''} &rarr;
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Stable institutional absorption across LQ45.</div>
                )}
              </div>
            </div>

            {/* Retail Traps Box */}
            <div style={{
              background: 'rgba(239, 68, 68, 0.08)',
              border: '1px solid rgba(239, 68, 68, 0.3)',
              borderRadius: '12px',
              padding: '1rem',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.6rem' }}>
                <span style={{ fontSize: '1.1rem' }}>🔴</span>
                <strong style={{ color: '#f87171', fontSize: '0.9rem' }}>Retail Traps (Avoid)</strong>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                {retailTraps.length > 0 ? (
                  retailTraps.map((item: any) => {
                    const code = item.StockCode || item.code;
                    return (
                      <div
                        key={code}
                        onClick={() => {
                          onSelectStock(code);
                          onClose();
                        }}
                        style={{
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'center',
                          padding: '0.4rem 0.6rem',
                          borderRadius: '6px',
                          background: 'rgba(255, 255, 255, 0.04)',
                          cursor: 'pointer',
                        }}
                        className="table-row-hover"
                      >
                        <span style={{ fontWeight: 700, color: '#f8fafc', fontSize: '0.85rem' }}>{code}</span>
                        <span style={{ color: '#f87171', fontSize: '0.75rem', fontWeight: 600 }}>
                          Distributing &rarr;
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>No severe retail distribution spikes detected.</div>
                )}
              </div>
            </div>

            {/* Alpha Compounders Box */}
            <div style={{
              background: 'rgba(56, 189, 248, 0.08)',
              border: '1px solid rgba(56, 189, 248, 0.3)',
              borderRadius: '12px',
              padding: '1rem',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.6rem' }}>
                <span style={{ fontSize: '1.1rem' }}>💎</span>
                <strong style={{ color: '#38bdf8', fontSize: '0.9rem' }}>Quality Compounders</strong>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                {alphaChampions.length > 0 ? (
                  alphaChampions.map((item: any) => {
                    const code = item.StockCode;
                    return (
                      <div
                        key={code}
                        onClick={() => {
                          onSelectStock(code);
                          onClose();
                        }}
                        style={{
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'center',
                          padding: '0.4rem 0.6rem',
                          borderRadius: '6px',
                          background: 'rgba(255, 255, 255, 0.04)',
                          cursor: 'pointer',
                        }}
                        className="table-row-hover"
                      >
                        <span style={{ fontWeight: 700, color: '#f8fafc', fontSize: '0.85rem' }}>{code}</span>
                        <span style={{ color: '#38bdf8', fontSize: '0.75rem', fontWeight: 600 }}>
                          ROE {item.ROE}% &rarr;
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Scanning multi-factor alpha...</div>
                )}
              </div>
            </div>
          </div>

          {/* 2. Bandarmology Dominance Summary Bar */}
          {bandarmologySum && (
            <div style={{
              background: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              borderRadius: '12px',
              padding: '1rem 1.25rem',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              flexWrap: 'wrap',
              gap: '1rem',
            }}>
              <div>
                <div style={{ fontSize: '0.75rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 700 }}>
                  Bandarmology Broker Dominance Ratio
                </div>
                <div style={{ fontSize: '1rem', fontWeight: 700, color: '#f8fafc', marginTop: '0.2rem' }}>
                  Top 3 Brokers Control <span style={{ color: '#facc15' }}>{bandarmologySum.cr3_pct != null ? `${bandarmologySum.cr3_pct}%` : '—'}</span> of Market Volume
                </div>
              </div>

              <div style={{ display: 'flex', gap: '1.5rem' }}>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>CR1 Dominance</div>
                  <div style={{ fontSize: '0.9rem', fontWeight: 700, color: '#38bdf8' }}>{bandarmologySum.cr1_pct != null ? `${bandarmologySum.cr1_pct}%` : '—'}</div>
                </div>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>CR5 Dominance</div>
                  <div style={{ fontSize: '0.9rem', fontWeight: 700, color: '#a855f7' }}>{bandarmologySum.cr5_pct != null ? `${bandarmologySum.cr5_pct}%` : '—'}</div>
                </div>
                <div>
                  <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>Inst / Retail Ratio</div>
                  <div style={{ fontSize: '0.9rem', fontWeight: 700, color: '#34d399' }}>{bandarmologySum.institutional_to_retail_ratio != null ? `${bandarmologySum.institutional_to_retail_ratio}x` : '—'}</div>
                </div>
              </div>
            </div>
          )}

          {/* 3. WhatsApp / Telegram Flash Preview Box */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
              <span style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                WhatsApp / Telegram Shareable Flash Preview
              </span>
              <button
                onClick={handleCopy}
                style={{
                  background: 'none',
                  border: 'none',
                  color: copied ? '#34d399' : '#38bdf8',
                  fontSize: '0.75rem',
                  fontWeight: 700,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                }}
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                <span>{copied ? 'Copied!' : 'Copy Text'}</span>
              </button>
            </div>

            <pre style={{
              background: '#040711',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              borderRadius: '10px',
              padding: '1rem',
              color: '#cbd5e1',
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: '0.78rem',
              lineHeight: 1.5,
              whiteSpace: 'pre-wrap',
              overflowX: 'auto',
              maxHeight: '220px',
            }}>
              {generateFlashText()}
            </pre>
          </div>

          {/* Footer Note */}
          <div style={{ fontSize: '0.75rem', color: '#64748b', textAlign: 'center' }}>
            Quantitative decision engine running multi-factor ranking over Parquet time-series. Not formal investment advice.
          </div>
        </div>
      </div>
    </div>
  );
};
